# Generated by Django 5.2.3 on 2025-06-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('duration_days', models.PositiveIntegerField()),
                ('num_people', models.PositiveIntegerField()),
                ('accommodation_type', models.CharField(choices=[('economique', 'Économique'), ('standard', 'Standard'), ('luxe', 'Luxe')], max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('mg', 'Malgache')], default='fr', max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
