# Generated by Django 5.2.3 on 2025-06-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
